### ISSUE TITLE
Add timestamps to the chat

### ISSUE THREAD

**Issue by BartWillems** [kkuchta/css-only-chat#15] opened 2019-05-09 08:22 UTC
I've replaced all my chat clients with this one as it's very lightweight and scales surprisingly well.

I have only 1 issue, I can't see when a message was sent :thinking:

**Comment by kkuchta** [comment] 2019-05-10 14:27
Time is an illusion.  Closing as not a bug because in reality all things happen simultaneously.

**Closed by kkuchta** 2019-05-10 14:27 UTC

**Comment by downloadpizza** [comment] 2019-07-27 16:27
@BartWillems Make a fork, do it yourself, I didn't know Ruby until I started to look at this and I still did a PR. Don't be afraid to try
